#!/usr/bin/env python

obj = bld(
	features  = 'cc cprogram',
	uselib    = 'GLIB LIBXML2 SDL GTK',
	target    = 'dfsound',
	lib       = ['SDL_mixer','mingw32','SDLmain'],
	includes  = '.. .',
	linkflags = ['-g'],
	ccflags   = ['-g']
)
obj.find_sources_in_dirs('.')
