#!/usr/bin/env python

obj = bld(
	features  = 'cc cprogram',
	uselib    = 'GLIB LIBXML2 SDL GTK',
	target    = 'dfsound',
	lib       = ['SDL_mixer'],
	defines   = ['VERSION="'+bld.env['VERSION']+'"'],
	linkflags = ['-g'],
	ccflags   = ['-g']
)
obj.find_sources_in_dirs('.')
